### ISSUE TITLE
可否添加例程中用到的相关图片资源

### ISSUE THREAD

**Issue by mindcont** [willard-yuan/pcv-book-code#3]
偶然搜索到，觉得很好，希望可以加入一些例程中用到的相关图片资源

> http://programmingcomputervision.com/

**Comment by willard-yuan** [comment]
@mindcont 全书的图片资源可以在[这里](http://pan.baidu.com/share/link?shareid=4059473268&uk=3440544532)下载，另外部分章节可以在这里查看[pcvwithpython](https://github.com/willard-yuan/pcvwithpython)(本来是有网页的，最近因为想把博客重新整理一下，所以导致网页目前不可访问)
